### ISSUE TITLE
Set up environment

### ISSUE THREAD

**Issue by agamsanghera** [UBC-MDS/group04#25]
@diwanashita @ch3ch20h will be working on creating and maintaining the environment for the rest of the course

**Comment by diwanashita** [comment]
I will create the Docker Hub public repo and add all collaborators. 
Please add your usernames to this thread to be added as collaborators.

**Comment by agendazhang** [comment]
My username is agendazhang

**Comment by agendazhang** [comment]
@diwanashita 
1. Please test build the docker on local first, it will be much faster to catch any build issues
2. The reason the build failed was because the python version had some dependency conflict with conda (pic 1). This was resolved by downgrading the python version to 3.11

<img width="686" alt="113 5 stdout" src="https://github.com/user-attachments/assets/2e310a8b-ef64-4026-8444-be7e0d8e054c">

With the latest change, github action workflow is successful and the image should be published to dockerhub now

<img width="669" alt="image" src="https://github.com/user-attachments/assets/2615d74d-6777-49df-95e8-7756444053e8">

**Comment by agamsanghera** [comment]
I am working on fixing that workflow

**Comment by agendazhang** [comment]
@agamsanghera I have already fixed it
<img width="669" alt="image" src="https://github.com/user-attachments/assets/3ffd48ff-5f52-40d5-abee-e8d760ff8179">

**Comment by agamsanghera** [comment]
I see, thanks

**Comment by ch3ch20h** [comment]
> I will create the Docker Hub public repo and add all collaborators. Please add your usernames to this thread to be added as collaborators.

My username is liuyichun95

**Comment by agamsanghera** [comment]
@agendazhang thanks for the detailed documentation on using docker, and finishing up the setup, I will add all of you guys to the dockerhub repo too

**Comment by diwanashita** [comment]
my username is adiwan02
