### ISSUE TITLE
Converted ipynb files to qmd files 

### ISSUE THREAD

**Issue by ch3ch20h** [UBC-MDS/group04#46]
I have converted the ipynb files in notebooks folder to eda_analysis.qmd, data_validation.qmd, and analysis.qmd, pushed to branch quarto, and created a pull request. Can someone review the request?

**Comment by agamsanghera** [comment]
I had a look at the files you created, thank you very much for the work, can you please make it into one file rather than 3 separate ones, you can take a look at [example repo](https://github.com/ttimbers/breast-cancer-predictor/blob/2.0.0/reports). and also create a new folder called reports to work with that please
